name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Genera diariamente
  workflow_dispatch:     # Permite ejecución manual

permissions:
  contents: write         # 🔑 Necesario para hacer push
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: SrRusian
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
